import { item } from "@/types/Item";

export const products: item[] = [
  {
    id: 1,
    name: "Smartphone X Pro",
    currentPrice: 999.99,
    originalPrice: 1199.99,
    image:
      "https://m.media-amazon.com/images/I/71mruAvDR7L._AC_UY436_FMwebp_QL65_.jpg",
    condition: "Working",
    sellerName: "TechGuru",
    sellerAvatar: "https://example.com/avatars/techguru.jpg",
    rating: 3.8,
    timeListedAgo: "2 days ago",
    distance: 30,
  },
  {
    id: 2,
    name: "4K LED TV",
    currentPrice: 499.99,
    originalPrice: 599.99,
    image:
      "https://m.media-amazon.com/images/I/71x1PocPi8L._AC_UY436_FMwebp_QL65_.jpg",
    condition: "Excellent",
    sellerName: "HomeElectronics",
    sellerAvatar: "https://example.com/avatars/homeelectronics.jpg",
    rating: 4.5,
    timeListedAgo: "1 week ago",
    distance: 1,
  },
  {
    id: 3,
    name: "Wireless Headphones",
    currentPrice: 199.99,
    originalPrice: 249.99,
    image:
      "https://m.media-amazon.com/images/I/61qlqvTsocL._AC_UY436_FMwebp_QL65_.jpg",
    condition: "Comfortable",
    sellerName: "AudioMaster",
    sellerAvatar: "https://example.com/avatars/audiomaster.jpg",
    rating: 1.3,
    timeListedAgo: "5 days ago",
    distance: 79,
  },
  {
    id: 4,
    name: "Gaming Laptop YZ",
    currentPrice: 1299.99,
    originalPrice: 1499.99,
    image:
      "https://m.media-amazon.com/images/I/51PQfSwIqyL._AC_UY436_FMwebp_QL65_.jpg",
    condition: "Comfortable",
    sellerName: "GamerHub",
    sellerAvatar: "https://example.com/avatars/gamerhub.jpg",
    rating: 2.9,
    timeListedAgo: "3 days ago",
    distance: 53,
  },
  {
    id: 5,
    name: "Smartwatch Series 5",
    currentPrice: 299.99,
    originalPrice: 349.99,
    image: `https://m.media-amazon.com/images/I/51dTWFTAnaL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "WearableTech",
    sellerAvatar: "https://example.com/avatars/wearabletech.jpg",
    rating: 4.7,
    timeListedAgo: "4 days ago",
    distance: 27,
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    currentPrice: 89.99,
    originalPrice: 129.99,
    image:
      "https://m.media-amazon.com/images/I/61r4hdFT9ML._AC_UL640_FMwebp_QL65_.jpg",
    condition: "Comfortable",
    sellerName: "SoundWave",
    sellerAvatar: "https://example.com/avatars/soundwave.jpg",
    rating: 4.6,
    timeListedAgo: "6 days ago",
    distance: 89,
  },
  {
    id: 7,
    name: "Laptop Stand",
    currentPrice: 39.99,
    originalPrice: 49.99,
    image: `https://m.media-amazon.com/images/I/61WeCZ-WvrL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Just Bought",
    sellerName: "OfficeEssentials",
    sellerAvatar: "https://example.com/avatars/officeessentials.jpg",
    rating: 2.2,
    timeListedAgo: "1 month ago",
    distance: 67,
  },
  {
    id: 8,
    name: "Digital Camera Z7",
    currentPrice: 799.99,
    originalPrice: 999.99,
    image:
      "https://m.media-amazon.com/images/I/71Q0fB9WK1L._AC_UL640_FMwebp_QL65_.jpg",
    condition: "Working",
    sellerName: "PhotoExpert",
    sellerAvatar: "https://example.com/avatars/photoexpert.jpg",
    rating: 3.8,
    timeListedAgo: "2 weeks ago",
    distance: 57,
  },
  {
    id: 9,
    name: "Smart Home Hub",
    currentPrice: 149.99,
    originalPrice: 199.99,
    image: `https://m.media-amazon.com/images/I/61hLb3DSS4L._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Working",
    sellerName: "SmartLiving",
    sellerAvatar: "https://example.com/avatars/smartliving.jpg",
    rating: 3.5,
    timeListedAgo: "5 days ago",
    distance: 87,
  },
  {
    id: 10,
    name: "VR Headset Model X",
    currentPrice: 399.99,
    originalPrice: 499.99,
    image: `https://m.media-amazon.com/images/I/61L+PtUYDUL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Working",
    sellerName: "VRWorld",
    sellerAvatar: "https://example.com/avatars/vrworld.jpg",
    rating: 4.7,
    timeListedAgo: "1 day ago",
    distance: 12,
  },
  {
    id: 11,
    name: "Portable SSD 1TB",
    currentPrice: 119.99,
    originalPrice: 149.99,
    image: `https://m.media-amazon.com/images/I/51ykbSj-eoL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "StorageMasters",
    sellerAvatar: "https://example.com/avatars/storagemasters.jpg",
    rating: 1.6,
    timeListedAgo: "3 weeks ago",
    distance: 19,
  },
  {
    id: 12,
    name: "Action Camera Pro",
    currentPrice: 299.99,
    originalPrice: 349.99,
    image: `https://m.media-amazon.com/images/I/51NzQ3q8VtL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Comfortable",
    sellerName: "AdventureGear",
    sellerAvatar: "https://example.com/avatars/adventuregear.jpg",
    rating: 1.8,
    timeListedAgo: "2 weeks ago",
    distance: 22,
  },
  {
    id: 13,
    name: "Gaming Mouse",
    currentPrice: 59.99,
    originalPrice: 79.99,
    image: `https://m.media-amazon.com/images/I/71hC1byRyKL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Just Bought",
    sellerName: "GamerGear",
    sellerAvatar: "https://example.com/avatars/gamergear.jpg",
    rating: 4.4,
    timeListedAgo: "1 week ago",
    distance: 44,
  },
  {
    id: 14,
    name: "Wireless Charger",
    currentPrice: 29.99,
    originalPrice: 39.99,
    image: `https://m.media-amazon.com/images/I/71+YhObKmEL._AC_UY436_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "ChargeStation",
    sellerAvatar: "https://example.com/avatars/chargestation.jpg",
    rating: 4.5,
    timeListedAgo: "4 days ago",
    distance: 98,
  },
  {
    id: 15,
    name: "Smart TV Stick",
    currentPrice: 49.99,
    originalPrice: 59.99,
    image: `https://m.media-amazon.com/images/I/71QCqjg5j8L._AC_UY436_QL65_.jpg`,
    condition: "Comfortable",
    sellerName: "MediaSolutions",
    sellerAvatar: "https://example.com/avatars/mediasolutions.jpg",
    rating: 3.6,
    timeListedAgo: "2 days ago",
    distance: 85,
  },
  {
    id: 16,
    name: "Fitness Tracker",
    currentPrice: 79.99,
    originalPrice: 99.99,
    image: `https://m.media-amazon.com/images/I/71-e4Mg14rL._AC_UY436_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "FitTech",
    sellerAvatar: "https://example.com/avatars/fittech.jpg",
    rating: 4.7,
    timeListedAgo: "1 week ago",
    distance: 19,
  },
  {
    id: 17,
    name: "Smart Light Bulb",
    currentPrice: 19.99,
    originalPrice: 29.99,
    image:
      "https://m.media-amazon.com/images/I/51VcpeUZjVL._AC_UY436_QL65_.jpg",
    condition: "Working",
    sellerName: "HomeAutomation",
    sellerAvatar: "https://example.com/avatars/homeautomation.jpg",
    rating: 3.3,
    timeListedAgo: "5 days ago",
    distance: 52,
  },
  {
    id: 18,
    name: "Noise-Canceling Headphones",
    currentPrice: 249.99,
    originalPrice: 299.99,
    image: `https://picsum.photos/id/18/200/300`,
    condition: "Just Bought",
    sellerName: "AudioExperts",
    sellerAvatar: "https://example.com/avatars/audioexperts.jpg",
    rating: 3.9,
    timeListedAgo: "3 days ago",
    distance: 94,
  },
  {
    id: 19,
    name: "Drone Pro",
    currentPrice: 599.99,
    originalPrice: 699.99,
    image: `https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_UY436_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "FlyHigh",
    sellerAvatar: "https://example.com/avatars/flyhigh.jpg",
    rating: 2.8,
    timeListedAgo: "1 month ago",
    distance: 8,
  },
  {
    id: 20,
    name: "Electric Toothbrush",
    currentPrice: 89.99,
    originalPrice: 109.99,
    image: `https://m.media-amazon.com/images/I/61xKiCADfpL._AC_UY436_QL65_.jpg`,
    condition: "Comfortable",
    sellerName: "HealthGadgets",
    sellerAvatar: "https://example.com/avatars/healthgadgets.jpg",
    rating: 4.4,
    timeListedAgo: "2 weeks ago",
    distance: 4,
  },
  {
    id: 21,
    name: "Smartphone X Pro",
    currentPrice: 999.99,
    originalPrice: 1199.99,
    image: `https://m.media-amazon.com/images/I/819eNuXA-NL._AC_UY436_QL65_.jpg`,
    condition: "Working",
    sellerName: "TechGuru",
    sellerAvatar: "https://example.com/avatars/techguru.jpg",
    rating: 3.8,
    timeListedAgo: "2 days ago",
    distance: 48,
  },
  {
    id: 22,
    name: "Stylish Dress",
    currentPrice: 49.99,
    originalPrice: 69.99,
    image: `https://m.media-amazon.com/images/I/715kpqCUv9L._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "Fashionista",
    sellerAvatar: "https://example.com/avatars/fashionista.jpg",
    rating: 4.5,
    timeListedAgo: "1 week ago",
    distance: 99,
  },
  {
    id: 23,
    name: "Stainless Steel Cookware Set",
    currentPrice: 199.99,
    originalPrice: 249.99,
    image: `https://m.media-amazon.com/images/I/71MwDnn-ZaL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "HomeEssentials",
    sellerAvatar: "https://example.com/avatars/homeessentials.jpg",
    rating: 4.7,
    timeListedAgo: "3 days ago",
    distance: 3,
  },
  {
    id: 24,
    name: "Facial Moisturizer",
    currentPrice: 29.99,
    originalPrice: 39.99,
    image: `https://m.media-amazon.com/images/I/81u+lUSZRDL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Working",
    sellerName: "BeautyHub",
    sellerAvatar: "https://example.com/avatars/beautyhub.jpg",
    rating: 1.6,
    timeListedAgo: "5 days ago",
    distance: 29,
  },
  {
    id: 25,
    name: "Camping Tent",
    currentPrice: 149.99,
    originalPrice: 179.99,
    image: `https://m.media-amazon.com/images/I/81Tfy967TKL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Comfortable",
    sellerName: "OutdoorGear",
    sellerAvatar: "https://example.com/avatars/outdoorgear.jpg",
    rating: 4.8,
    timeListedAgo: "2 weeks ago",
    distance: 72,
  },
  {
    id: 26,
    name: "Mystery Novel",
    currentPrice: 15.99,
    originalPrice: 19.99,
    image: `https://m.media-amazon.com/images/I/81OmhFfS-hL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Just Bought",
    sellerName: "BookStore",
    sellerAvatar: "https://example.com/avatars/bookstore.jpg",
    rating: 3.5,
    timeListedAgo: "1 month ago",
    distance: 69,
  },
  {
    id: 27,
    name: "Board Game Set",
    currentPrice: 29.99,
    originalPrice: 39.99,
    image: `https://m.media-amazon.com/images/I/91xnO7qHAeL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Comfortable",
    sellerName: "ToyMasters",
    sellerAvatar: "https://example.com/avatars/toymasters.jpg",
    rating: 2.4,
    timeListedAgo: "3 days ago",
    distance: 43,
  },
  {
    id: 28,
    name: "Yoga Mat",
    currentPrice: 24.99,
    originalPrice: 34.99,
    image: `https://m.media-amazon.com/images/I/71bEYFvV5lL._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Working",
    sellerName: "FitLife",
    sellerAvatar: "https://example.com/avatars/fitlife.jpg",
    rating: 4.7,
    timeListedAgo: "2 weeks ago",
    distance: 77,
  },
  {
    id: 29,
    name: "Car Vacuum Cleaner",
    currentPrice: 89.99,
    originalPrice: 109.99,
    image: `https://m.media-amazon.com/images/I/81+9LRBzz6L._AC_UY436_FMwebp_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "AutoAccessories",
    sellerAvatar: "https://example.com/avatars/autoaccessories.jpg",
    rating: 4.6,
    timeListedAgo: "1 month ago",
    distance: 4,
  },
  {
    id: 30,
    name: "Wooden Dining Table",
    currentPrice: 599.99,
    originalPrice: 699.99,
    image: `https://m.media-amazon.com/images/I/41GYfdZdqlL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Comfortable",
    sellerName: "FurnitureMart",
    sellerAvatar: "https://example.com/avatars/furnituremart.jpg",
    rating: 3.9,
    timeListedAgo: "2 weeks ago",
    distance: 3,
  },
  {
    id: 31,
    name: "Organic Snacks",
    currentPrice: 19.99,
    originalPrice: 24.99,
    image:
      "https://m.media-amazon.com/images/I/61Kfqt-h5-L._AC_UY436_FMwebp_QL65_.jpg",
    condition: "Excellent",
    sellerName: "HealthyEats",
    sellerAvatar: "https://example.com/avatars/healthyeats.jpg",
    rating: 4.5,
    timeListedAgo: "3 days ago",
    distance: 1,
  },
  {
    id: 32,
    name: "Baby Stroller",
    currentPrice: 249.99,
    originalPrice: 299.99,
    image: `https://m.media-amazon.com/images/I/51FRsJvhucL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Working",
    sellerName: "BabyCare",
    sellerAvatar: "https://example.com/avatars/babycare.jpg",
    rating: 1.8,
    timeListedAgo: "1 month ago",
    distance: 9,
  },
  {
    id: 33,
    name: "Dog Bed",
    currentPrice: 49.99,
    originalPrice: 69.99,
    image: `https://m.media-amazon.com/images/I/51nO2BujwnL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Just Bought",
    sellerName: "PetParadise",
    sellerAvatar: "https://example.com/avatars/petparadise.jpg",
    rating: 4.4,
    timeListedAgo: "2 weeks ago",
    distance: 18,
  },
  {
    id: 34,
    name: "Gold Necklace",
    currentPrice: 199.99,
    originalPrice: 249.99,
    image: `https://m.media-amazon.com/images/I/51ZtF7SAYqL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Comfortable",
    sellerName: "JewelryBox",
    sellerAvatar: "https://example.com/avatars/jewelrybox.jpg",
    rating: 1.9,
    timeListedAgo: "3 weeks ago",
    distance: 84,
  },
  {
    id: 35,
    name: "Gaming Laptop",
    currentPrice: 1299.99,
    originalPrice: 1499.99,
    image:
      "https://m.media-amazon.com/images/I/5190fG9PqOL._AC_UL640_FMwebp_QL65_.jpg",
    condition: "Working",
    sellerName: "TechWorld",
    sellerAvatar: "https://example.com/avatars/techworld.jpg",
    rating: 4.8,
    timeListedAgo: "1 day ago",
    distance: 66,
  },
  {
    id: 36,
    name: "Smartphone Case",
    currentPrice: 19.99,
    originalPrice: 24.99,
    image: `https://m.media-amazon.com/images/I/71JNvx2i7QL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Excellent",
    sellerName: "GadgetShop",
    sellerAvatar: "https://example.com/avatars/gadgetshop.jpg",
    rating: 3.5,
    timeListedAgo: "4 days ago",
    distance: 58,
  },
  {
    id: 37,
    name: "DSLR Camera",
    currentPrice: 899.99,
    originalPrice: 999.99,
    image: `https://m.media-amazon.com/images/I/51w-cGDjSvL._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Working",
    sellerName: "PhotoWorld",
    sellerAvatar: "https://example.com/avatars/photonworld.jpg",
    rating: 2.9,
    timeListedAgo: "2 weeks ago",
    distance: 78,
  },
  {
    id: 38,
    name: "5 Star",
    currentPrice: 4.99,
    originalPrice: 4.99,
    image: `https://m.media-amazon.com/images/I/51IvuJbkP-L._AC_UL640_FMwebp_QL65_.jpg`,
    condition: "Just Bought",
    sellerName: "Vardaan",
    sellerAvatar: "https://example.com/avatars/photonworld.jpg",
    rating: 5,
    timeListedAgo: "1 day ago",
    distance: 0,
  },
];
