export const tags = [
  "Electronics",
  "Fashion",
  "Home & Kitchen",
  "Beauty & Personal Care",
  "Sports & Outdoors",
  "Books & Media",
  "Toys & Games",
  "Health & Wellness",
  "Automotive",
  "Furniture",
  "Groceries & Food",
  "Baby Products",
  "Pet Supplies",
  "Jewelry & Accessories",
  "Computers & Accessories",
  "Mobile Phones & Accessories",
  "Cameras & Photography",
  "Luggage & Travel Gear",
  "Musical Instruments",
  "Office Supplies",
  "Tools & Home Improvement",
  "Video Games & Consoles",
  "Watches",
  "Appliances",
  "Stationery & Craft",
  "Garden & Outdoor",
  "Fitness Equipment",
  "Bags & Wallets",
  "Footwear",
  "Movies & TV Shows",
  "Art & Collectibles",
  "Software",
  "Gift Cards",
  "Mobile Phones",
  "Laptops & Notebooks",
  "Tablets",
  "Desktop Computers",
  "Smartwatches",
  "Televisions & Home Entertainment",
  "Cameras & Photography",
  "Headphones & Earbuds",
  "Wearable Technology",
  "Gaming Consoles & Accessories",
  "Drones & Action Cameras",
  "Speakers & Home Audio Systems",
  "Monitors & Displays",
  "Printers & Scanners",
  "Computer Components & Accessories",
  "Smart Home Devices",
  "Networking Devices (Routers & Modems)",
  "Power Banks & Charging Accessories",
  "External Storage Devices",
  "Bluetooth Devices & Accessories",
  "Projectors",
  "VR (Virtual Reality) Devices",
  "Car Electronics & GPS",
  "Smart Glasses",
  "Camera Drones",
  "Home Security & Surveillance"
];
